# Generated by Django 6.0.4 on 2026-05-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotline', models.CharField(blank=True, max_length=50)),
                ('zalo_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_map_embed', models.TextField(blank=True)),
                ('policy_buying', models.TextField(blank=True)),
                ('policy_shipping', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'site config',
                'verbose_name_plural': 'site config',
            },
        ),
    ]
