# Generated by Django 6.0.4 on 2026-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('bg_color', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
