# Generated by Django 6.0.4 on 2026-05-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
