# Generated by Django 6.0.4 on 2026-05-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_banner_subtitle_en_banner_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
