# Generated by Django 6.0.4 on 2026-05-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_siteconfig_about_siteconfig_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='location',
            field=models.CharField(blank=True, default='home', help_text='Vị trí hiển thị banner. Nhập nhiều vị trí cách nhau bằng dấu phẩy, ví dụ: home,products', max_length=50),
        ),
    ]
