# Generated by Django 6.0.4 on 2026-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='promotion_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
