# Generated by Django 6.0.4 on 2026-05-08 15:26

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.product_image_upload_path),
        ),
    ]
